<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>l1_bringup</name>
  <version>0.1.0</version>
  <description>Configurable launch and configuration for the Unitree L1 project.</description>
  <maintainer email="103388150+pokepascu@users.noreply.github.com">Pascual Asio Serrano</maintainer>
  <license>MIT</license>
  <url type="repository">https://github.com/pokepascu/Unitree-L1-ROS2-Octomap</url>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>l1_monitor</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>unitree_lidar_ros2</exec_depend>

  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
