name: unitree-l1

services:
  dev:
    image: unitree-l1:humble-v1.0.16
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        HOST_UID: "${HOST_UID:-1000}"
        HOST_GID: "${HOST_GID:-1000}"
    container_name: unitree_l1_humble
    init: true
    tty: true
    stdin_open: true
    working_dir: /workspace/ros2_ws
    environment:
      ROS_DOMAIN_ID: "${ROS_DOMAIN_ID:-42}"
    volumes:
      - type: bind
        source: ..
        target: /workspace
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    command: ["bash"]
