#!/usr/bin/env python3
"""Convert the project's constrained manual Markdown into styled groff."""

from __future__ import annotations

import re
import sys
from pathlib import Path


SPECIAL_CHARACTERS = {
    "\u00a0": " ",
    "\u2018": "'",
    "\u2019": "'",
    "\u201c": '"',
    "\u201d": '"',
    "\u2013": "-",
    "\u2014": "--",
    "\u2026": "...",
    "\u2190": "<-",
    "\u2192": "->",
    "\u2194": "<->",
    "\u2264": "<=",
    "\u2265": ">=",
    "\u2248": "~",
    "\u00d7": "x",
}


def parse_front_matter(text: str) -> tuple[dict[str, str], list[str]]:
    """Return simple key/value front matter and the remaining Markdown lines."""
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        raise ValueError("manual source must begin with --- front matter")
    metadata: dict[str, str] = {}
    end = None
    for index, line in enumerate(lines[1:], start=1):
        if line.strip() == "---":
            end = index
            break
        if ":" not in line:
            raise ValueError(f"invalid front-matter line: {line}")
        key, value = line.split(":", 1)
        metadata[key.strip()] = value.strip()
    if end is None:
        raise ValueError("manual front matter has no closing ---")
    required = {
        "document_type",
        "title",
        "subtitle",
        "edition",
        "prepared",
        "project_commit",
        "audience",
        "footer",
    }
    missing = sorted(required - metadata.keys())
    if missing:
        raise ValueError(f"missing front-matter keys: {', '.join(missing)}")
    return metadata, lines[end + 1 :]


def replace_special_characters(text: str) -> str:
    """Normalize punctuation unsupported by the PostScript core fonts."""
    for source, replacement in SPECIAL_CHARACTERS.items():
        text = text.replace(source, replacement)
    return text


def roff_literal(text: str, *, code: bool = False) -> str:
    """Escape literal text so it cannot become a groff request or escape."""
    text = replace_special_characters(text)
    text = text.replace("\\", r"\e")
    if code:
        text = text.replace("\t", "    ")
    if text.startswith((".", "'")):
        text = r"\&" + text
    return text


def inline_markup(text: str) -> str:
    """Render the small inline subset used by the manual sources."""
    text = replace_special_characters(text)
    pattern = re.compile(r"(`[^`]+`|\*\*[^*]+\*\*)")
    output: list[str] = []
    cursor = 0
    for match in pattern.finditer(text):
        output.append(roff_literal(text[cursor : match.start()]))
        token = match.group(0)
        if token.startswith("`"):
            output.append(r"\f[C]" + roff_literal(token[1:-1], code=True) + r"\fP")
        else:
            output.append(r"\f[HB]" + roff_literal(token[2:-2]) + r"\fP")
        cursor = match.end()
    output.append(roff_literal(text[cursor:]))
    rendered = "".join(output).replace('"', r"\(dq")
    if rendered.startswith((".", "'")):
        rendered = r"\&" + rendered
    return rendered


def roff_string(text: str) -> str:
    """Escape a plain value embedded directly in a groff definition."""
    return roff_literal(text).replace('"', r"\(dq")


def preamble(metadata: dict[str, str], source_name: str) -> str:
    """Build the shared A4 visual system and document cover."""
    footer = roff_string(metadata["footer"])
    title_lines = [roff_string(part.strip()) for part in metadata["title"].split("|")]
    subtitle_lines = [
        roff_string(part.strip()) for part in metadata["subtitle"].split("|")
    ]
    cover_title = "\n".join(title_lines)
    cover_subtitle = "\n".join(subtitle_lines)
    cover_title_count = len(title_lines)
    cover_subtitle_count = len(subtitle_lines)
    return rf""".\" Generated from {roff_string(source_name)}. Do not edit this file.
.po 1.55c
.ll 17.9c
.lt 17.9c
.pl 28.8c
.ps 9.4
.vs 12.4p
.ft H
.ad l
.hy 0
.kern 0
.defcolor Navy rgb #153B52
.defcolor Blue rgb #176B87
.defcolor Teal rgb #1B8A89
.defcolor Slate rgb #3F505A
.defcolor Pale rgb #EAF2F4
.defcolor Red rgb #A23832
.defcolor Amber rgb #9A6518
.ds DOCSHORT {footer}
.de HEADER
.ev header
.in 0
.ti 0
.ll 17.9c
.lt 17.9c
.ft H
.ps 7.3
.sp 0.22c
.tl '\m[Slate]\*[DOCSHORT]\m[black]''\m[Slate]\\n%\m[black]'
.sp 0.06c
\m[Pale]\l'17.9c'\m[black]
.sp 0.16c
.ev
..
.wh 0 HEADER
.de PARTBEGIN
.bp
.in 0
.ti 0
.sp 1.0c
.ne 7v
.ft HB
.ps 19
.vs 23p
\m[Navy]
..
.de PARTEND
\m[black]
.ps 9.4
.vs 12.4p
.ft H
.sp 0.55v
\m[Teal]\l'17.9c'\m[black]
.sp 0.50v
..
.de H2BEGIN
.in 0
.ti 0
.sp 0.76v
.ne 8v
.ft HB
.ps 14
.vs 17p
\m[Navy]
..
.de H2END
\m[black]
.ps 9.4
.vs 12.4p
.ft H
.sp 0.25v
..
.de H3BEGIN
.in 0
.ti 0
.sp 0.56v
.ne 7v
.ft HB
.ps 11.3
.vs 14p
\m[Blue]
..
.de H3END
\m[black]
.ps 9.4
.vs 12.4p
.ft H
.sp 0.18v
..
.de H4BEGIN
.in 0
.ti 0
.sp 0.42v
.ne 5v
.ft HB
.ps 9.8
\m[Navy]
..
.de H4END
\m[black]
.ps 9.4
.ft H
.sp 0.12v
..
.de PP
.sp 0.18v
.ft H
.ps 9.4
.vs 12.4p
..
.de CODEBEGIN
.sp 0.28v
.ne 3v
.in +0.42c
.ll -0.42c
.nf
.ft C
.ps 7.7
.vs 9.9p
\m[Slate]
..
.de CODEEND
\m[black]
.br
.ps 9.4
.vs 12.4p
.ft H
.fi
.ll +0.42c
.in -0.42c
.sp 0.28v
..
.de WARNINGBEGIN
.sp 0.34v
.ne 4v
.in +0.42c
.ll -0.42c
.ft HB
\m[Red]SAFETY / WARNING\m[black]
.br
.ft H
..
.de WARNINGEND
.br
.ll +0.42c
.in -0.42c
.sp 0.30v
..
.de NOTEBEGIN
.sp 0.30v
.ne 4v
.in +0.42c
.ll -0.42c
.ft HB
\m[Blue]ENGINEERING NOTE\m[black]
.br
.ft H
..
.de NOTEEND
.br
.ll +0.42c
.in -0.42c
.sp 0.26v
..
.de CHECKBEGIN
.sp 0.30v
.ne 4v
.in +0.42c
.ll -0.42c
.ft HB
\m[Teal]EXPECTED RESULT\m[black]
.br
.ft H
..
.de CHECKEND
.br
.ll +0.42c
.in -0.42c
.sp 0.26v
..
.de RULE
.sp 0.40v
\m[Teal]\l'17.9c'\m[black]
.sp 0.22v
..
.sp 0.65c
.ft HB
.ps 9
\m[Blue]{roff_string(metadata["document_type"]).upper()}\m[black]
.sp 1.35c
.ce {cover_title_count}
.ft HB
.ps 25
.vs 29p
\m[Navy]{cover_title}
\m[black]
.sp 0.62c
.ce {cover_subtitle_count}
.ft H
.ps 12.5
.vs 16p
\m[Blue]{cover_subtitle}
\m[black]
.sp 0.85c
.ce 1
\m[Teal]\l'12.5c'\m[black]
.sp 0.75c
.ce 4
.ft H
.ps 10
.vs 13.4p
{roff_string(metadata["edition"])}
Prepared {roff_string(metadata["prepared"])}
Validated project baseline {roff_string(metadata["project_commit"])}
Audience: {roff_string(metadata["audience"])}
.sp 1.0c
.ce 1
.ft HB
.ps 11
\m[Navy]DOCUMENT CONTROL\m[black]
.sp 0.30c
.in +2.4c
.ll -4.8c
.ft H
.ps 9.2
This document is generated from \f[C]{roff_string(source_name)}\fP.
Commands and paths describe the repository state identified above.
.br
.in -2.4c
.ll +4.8c
.sp 1.2c
.ce 1
.ft HB
.ps 10
\m[Red]Operate the powered LiDAR only after reading the safety section.\m[black]
.bp
.ps 9.4
.vs 12.4p
.ft H
"""


def emit_heading(output: list[str], level: int, text: str) -> None:
    macro = {1: "PART", 2: "H2", 3: "H3", 4: "H4"}[level]
    output.append(f".{macro}BEGIN\n")
    output.append(inline_markup(text) + "\n")
    output.append(f".{macro}END\n")


def emit_paragraph(output: list[str], text: str) -> None:
    output.append(".PP\n")
    output.append(inline_markup(text.strip()) + "\n")


def emit_list_item(output: list[str], text: str, number: str | None = None) -> None:
    output.append(".sp 0.10v\n")
    output.append(".in +0.62c\n")
    output.append(".ti -0.50c\n")
    if number is None:
        prefix = r"\m[Teal]\(bu\m[black]\h'0.14c'"
    else:
        prefix = rf"\m[Teal]{roff_literal(number)}.\m[black]\h'0.14c'"
    output.append(prefix + inline_markup(text) + "\n")
    output.append(".br\n")
    output.append(".in -0.62c\n")


def emit_callout(output: list[str], text: str) -> None:
    upper = text.upper()
    if upper.startswith(("WARNING:", "SAFETY:", "DANGER:")):
        begin, end = "WARNINGBEGIN", "WARNINGEND"
        body = text.split(":", 1)[1].strip()
    elif upper.startswith(("EXPECTED:", "SUCCESS:")):
        begin, end = "CHECKBEGIN", "CHECKEND"
        body = text.split(":", 1)[1].strip()
    else:
        begin, end = "NOTEBEGIN", "NOTEEND"
        body = text.split(":", 1)[1].strip() if ":" in text else text
    output.append(f".{begin}\n")
    output.append(inline_markup(body) + "\n")
    output.append(f".{end}\n")


def split_table_row(line: str) -> list[str]:
    return [cell.strip() for cell in line.strip().strip("|").split("|")]


def emit_table(output: list[str], rows: list[list[str]]) -> None:
    columns = len(rows[0])
    if columns == 2:
        widths = ["4.4c", "11.3c"]
    elif columns == 3:
        widths = ["3.7c", "2.7c", "8.0c"]
    elif columns == 4:
        widths = ["2.8c", "2.4c", "3.4c", "5.3c"]
    elif columns == 5:
        widths = ["1.6c", "2.1c", "2.7c", "3.2c", "4.1c"]
    else:
        raise ValueError(f"tables with {columns} columns are not supported")
    output.append(".sp 0.32v\n")
    output.append(".ps 7.9\n")
    output.append(".vs 10.1p\n")
    output.append(".TS\n")
    output.append("tab(@) allbox;\n")
    output.append(" ".join(f"lw({width})" for width in widths) + ".\n")

    def table_line(cells: list[str], *, header: bool = False) -> None:
        rendered: list[str] = []
        for cell in cells:
            content = inline_markup(cell)
            content = content.replace("/", r"/\:").replace("_", r"_\:")
            if header:
                content = r"\f[HB]\m[Navy]" + content + r"\m[black]\fP"
            rendered.append("T{\n" + content + "\nT}")
        output.append("@".join(rendered) + "\n")

    table_line(rows[0], header=True)
    for row in rows[1:]:
        table_line(row)
    output.append(".TE\n")
    output.append(".ps 9.4\n")
    output.append(".vs 12.4p\n")
    output.append(".sp 0.30v\n")


def convert(markdown_lines: list[str]) -> str:
    """Convert the documented Markdown subset into groff source."""
    output: list[str] = []
    paragraph: list[str] = []
    in_code = False
    first_title_seen = False
    index = 0

    def flush_paragraph() -> None:
        if paragraph:
            emit_paragraph(output, " ".join(line.strip() for line in paragraph))
            paragraph.clear()

    while index < len(markdown_lines):
        line = markdown_lines[index].rstrip()

        if line.startswith("```"):
            flush_paragraph()
            if in_code:
                output.append(".CODEEND\n")
                in_code = False
            else:
                output.append(".CODEBEGIN\n")
                in_code = True
            index += 1
            continue

        if in_code:
            output.append(roff_literal(line, code=True) + "\n")
            index += 1
            continue

        if (
            "|" in line
            and index + 1 < len(markdown_lines)
            and re.fullmatch(
                r"\s*\|?\s*:?-{3,}:?\s*(\|\s*:?-{3,}:?\s*)+\|?\s*",
                markdown_lines[index + 1],
            )
        ):
            flush_paragraph()
            table_rows = [split_table_row(line)]
            index += 2
            while index < len(markdown_lines):
                candidate = markdown_lines[index].rstrip()
                if not candidate.strip() or "|" not in candidate:
                    break
                row = split_table_row(candidate)
                if len(row) != len(table_rows[0]):
                    break
                table_rows.append(row)
                index += 1
            emit_table(output, table_rows)
            continue

        heading = re.match(r"^(#{1,4})\s+(.*)$", line)
        if heading:
            flush_paragraph()
            level = len(heading.group(1))
            if level == 1 and not first_title_seen:
                first_title_seen = True
            else:
                emit_heading(output, level, heading.group(2).strip())
            index += 1
            continue

        if line.strip() == "---":
            flush_paragraph()
            output.append(".RULE\n")
            index += 1
            continue

        if line.strip() == "<!-- PDF_PAGE_BREAK -->":
            flush_paragraph()
            output.append(".bp\n")
            index += 1
            continue

        if line.strip() == "<!-- PDF_KEEP_NEXT -->":
            flush_paragraph()
            output.append(".ne 8v\n")
            index += 1
            continue

        if line.startswith("> "):
            flush_paragraph()
            callout_lines: list[str] = []
            while (
                index < len(markdown_lines)
                and markdown_lines[index].rstrip().startswith("> ")
            ):
                callout_lines.append(markdown_lines[index].rstrip()[2:].strip())
                index += 1
            emit_callout(output, " ".join(callout_lines))
            continue

        numbered = re.match(r"^(\d+)\.\s+(.*)$", line)
        if numbered:
            flush_paragraph()
            emit_list_item(output, numbered.group(2), numbered.group(1))
            index += 1
            continue

        if line.startswith("- "):
            flush_paragraph()
            emit_list_item(output, line[2:])
            index += 1
            continue

        if not line.strip():
            flush_paragraph()
            index += 1
            continue

        paragraph.append(line)
        index += 1

    flush_paragraph()
    if in_code:
        raise ValueError("unclosed fenced code block")
    return "".join(output)


def main() -> int:
    if len(sys.argv) != 3:
        print("usage: render-manual.py SOURCE.md OUTPUT.roff", file=sys.stderr)
        return 2
    source = Path(sys.argv[1]).resolve()
    output = Path(sys.argv[2]).resolve()
    metadata, markdown_lines = parse_front_matter(source.read_text(encoding="utf-8"))
    rendered = preamble(metadata, source.name) + convert(markdown_lines)
    output.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
